---

# These tasks must be run on all Kubernetes nodes

- name: Install Docker
  yum:
    name: docker
    state: latest
  register: docker_install

- name: Make docker.service.d directory
  file:
    path: /usr/lib/systemd/system/docker.service.d
    state: directory

# This is important for mount propagation
- name: Set Docker mount flags
  copy:
    dest: /usr/lib/systemd/system/docker.service.d/mount_flags.conf
    content: |
      [Service]
      MountFlags=shared
  register: mount_flags_updated

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  when: mount_flags_updated is changed
  register: system_daemon_reload

- name: Allow dockerroot group to access Docker daemon
  copy:
    content: '{ "group": "dockerroot" }'
    dest: /etc/docker/daemon.json
  register: docker_daemon_config

- name: Restart Docker
  service:
    name: docker
    state: restarted
    enabled: yes
  when: >
    docker_install is changed or
    system_daemon_reload is changed or
    docker_daemon_config is changed

- name: Add RKE SSH user to dockerroot group
  user:
    name: "{{ rke_ssh_user }}"
    groups: [dockerroot]
    append: yes

- name: Ensure firewalld is started
  service:
    name: firewalld
    state: started
    enabled: yes

# The trusted zone allows all traffic
- name: Allow all traffic from cluster CIDR
  firewalld:
    zone: trusted
    source: "{{ cluster_cidr }}"
    state: enabled
    immediate: yes
    permanent: yes

- name: Create sysctl settings file for bridge settings
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  register: sysctl_k8s_conf

- name: Load new sysctl settings
  command: sysctl --system
  when: sysctl_k8s_conf is changed

- name: Ensure SELinux is disabled
  selinux:
    state: disabled

- name: Remove swap volumes from /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    # This should match all lines with an fstype of "swap"
    regexp: '^[^\s]+\s+[^\s]+\s+swap\s+'
  register: remove_swap_volumes

- name: Disable swap
  command: swapoff --all
  when: remove_swap_volumes is changed
